---
# tasks file for nginx

- name: "Install"
  ansible.builtin.include_role:
    name: geerlingguy.nginx

- name: 'Copy nginx config'
  notify: restart nginx
  ansible.builtin.template:
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root 
    mode: 0664

