###################
# XPASTE PLAYBOOK #
###################

---
- name: Deploy application
  hosts: app_server
  tags: deploy
  become: true
  vars:
    APP_NAME: "xpaste"
    APP_FOLDER: "/home/{{APP_NAME}}/app"
    APP_USER: "{{APP_NAME}}"

    APP_REPO: "git@gitlab.slurm.io:edu/xpaste_practicum.git"
    APP_REPO_LOCAL: "{{APP_NAME}}"

    SECRET_KEY_BASE: oh_my_secret
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: 1
    DB_HOST: 127.0.0.1
    DB_PORT: 5432
    DB_NAME: "{{APP_NAME}}_app"
    DB_USER: "{{APP_NAME}}_user"
    DB_PASSWORD: "xpaste_security#"




  pre_tasks:

    # Lazy lazy
    # - name: Install requirements
    #   become_user: user # Your local user
    #   delegate_to: localhost
    #   ignore_errors: yes
    #   ansible.builtin.command: |
    #     ansible-galaxy install -r requirements.yml      
    #   # ansible-galaxy collection install install -r requirements.yml   

    ## Используется локальный ansible с установленным git. Предполагается, что и с ключами все хорошо и красиво.
    ## Сервер приложения не должен знать ничего о репозитории и тем более не должен иметь ключей.
    - name: "LOCALHOST: Clone repo"
      delegate_to: 127.0.0.1
      become: false
      ansible.builtin.git:
        repo: "{{APP_REPO}}"
        dest: "{{APP_REPO_LOCAL}}"
        version: master

  handlers:

    - name: restart nginx
      service:
        name: "nginx"
        state: "reloaded"

  tasks:

    - name: "Postgres: Install"
      ansible.builtin.include_role:
        name: postgres

    - name: "App: Install"
      ansible.builtin.include_role:
        name: app

    - name: "Nginx: Install"
      ansible.builtin.include_role:
        name: nginx

    # Костыли пермишенов для nginx
    - name: Adding nginx to app group
      ansible.builtin.user:
        name: nginx
        groups: "{{APP_USER}}"
        append: yes
      notify: restart nginx

    - name: Set ownership
      ansible.builtin.file: 
        path: "/home/{{APP_USER}}"
        state: directory
        recurse: yes
        # mode: u=rwx,g=rwx,o=rwx
        mode: g+x
        owner: "{{APP_USER}}"
